name: Mule CI/CD Deployment

on:
  push:
    branches:
      - main # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Build
        run: mvn clean package -DskipMunitTests=true # Skip MUnit tests for build job, run in separate job for CI/CD pipeline

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Deploy application to Anypoint Platform
        run: mvn deploy -DmuleDeploy # Command to run the deployment goal
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
          ANYPOINT_ENV: ${{ secrets.ANYPOINT_ENV }}
          MULE_APP_NAME: ${{ secrets.MULE_APP_NAME }}
